#!/bin/sh

logger -t link-led "executed: ACTION=$ACTION INTERFACE=$INTERFACE"

case "$INTERFACE:$ACTION" in

    pppoe:ifdown|pppoe:ifup-failed)
        logger -t link-led "green:wlan ON"
        echo none > /sys/class/leds/green:wlan/trigger
        echo 1 > /sys/class/leds/green:wlan/brightness
        ;;

    pppoe:ifup)
        logger -t link-led "green:wlan OFF"
        echo none > /sys/class/leds/green:wlan/trigger
        echo 0 > /sys/class/leds/green:wlan/brightness
        ;;


    mape:ifdown|mape:ifup-failed)
        logger -t link-led "green:wan ON"
        echo none > /sys/class/leds/green:wan/trigger
        echo 1 > /sys/class/leds/green:wan/brightness
        ;;

    mape:ifup)
        logger -t link-led "green:wan OFF"
        echo none > /sys/class/leds/green:wan/trigger
        echo 0 > /sys/class/leds/green:wan/brightness
        ;;


    wan6:ifdown|wan6:ifup-failed)
        logger -t link-led "green:indicator ON"
        echo none > /sys/class/leds/green:indicator/trigger
        echo 1 > /sys/class/leds/green:indicator/brightness
        ;;

    wan6:ifup)
        logger -t link-led "green:indicator OFF"
        echo none > /sys/class/leds/green:indicator/trigger
        echo 0 > /sys/class/leds/green:indicator/brightness
        ;;

esac